### PR TITLE
Permutator err msg

### PR DESCRIPTION
**Pull request by dinga92**

### CODE REVIEW

**Comment by dinga92** [comment]
I just added the suggestions from #351, sorry for redundant PR

**Comment by nno** [comment]
Thanks for the code. Before we merge:
- if #351 is redundant, can you please close it?
- the test fails because of a type mismatch of the error thrown: ValueError versus RuntimeError. Can you please update the test code?

**Comment by yarikoptic** [comment]
coolio, so I have merged and fixed upthe test, and pushed.  So we are done with this one ;)

**Comment by dinga92** [comment]
Great, thanks :)

**Pull request merged**
