### PR TITLE
ENH,TST: add rsa.Regression measure with tests + small fix on typos [reopens #420]

### PR DESCRIPTION
**Pull request by mvdoc**
Reopens #420

### CODE REVIEW

**Comment by mvdoc** [comment]
Mmmh. The test fail for this 
```
FAIL: mvpa2.tests.test_benchmarks_hyperalignment.test_timesegments_classification
```

should I rebase on master?

**Comment by yarikoptic** [comment]
Probably a labile test, we might need to mark it as such... Just ignore

**Comment by yarikoptic** [comment]
Since we did plan to merge it after my rushed out bugfix release, could you @mvdoc please merge fresh master, and push -- let's see what tests would say

thanks in advance

**Comment by mvdoc** [comment]
done @yarikoptic

**Comment by yarikoptic** [comment]
thanks -- making yellow to turn green with my mental powers!

**Pull request merged**
