### PR TITLE
ENH & FIX for Procrustes

### PR DESCRIPTION
**Pull request by feilong**
Using the explicit tests by @yarikoptic .
Fixes another bug with the new tests.

### CODE REVIEW

**Comment by feilong** [comment]
Again, it's the scatter plot issue.
```
======================================================================
ERROR: mvpa2.tests.test_misc_scatter.test_plot_scatter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/PyMVPA/PyMVPA/mvpa2/tests/test_misc_scatter.py", line 56, in test_plot_scatter
    fig = plot_scatter(data2d, mask=mask)
  File "/home/travis/build/PyMVPA/PyMVPA/mvpa2/misc/plot/scatter.py", line 331, in plot_scatter
    _ = x[mask]; minx, maxx = np.min(_), np.max(_)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2214, in amin
    out=out, keepdims=keepdims)
  File "/usr/lib/python2.7/dist-packages/numpy/core/_methods.py", line 21, in _amin
    out=out, keepdims=keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
----------------------------------------------------------------------
```

**Comment by yarikoptic** [comment]
please file a separate issue for that failing test, ideally with the url to that particular build so we could see MVPA_SEED etc
and restart the failing build here -- it is just a random failure we need to catch

**Comment by yarikoptic** [comment]
ok, I think I fixed up for that failing test... merging now, thanks!

**Comment by feilong** [comment]
@yarikoptic Thanks for fixing the failing test!

**Pull request merged**
