### PR TITLE
NF: demeaning mapper

### PR DESCRIPTION
**Pull request by dinga92**

### CODE REVIEW

**Comment by hanke** [comment]
@dinga92 do you have time to address the few bits mentioned in this PR so we could merge it? Release is coming any day now.

**Comment by dinga92** [comment]
I am sorry, KI totally forgot baout this, I wont have time at all this week

**Comment by hanke** [comment]
@dinga92 I am on it.

**Comment by dinga92** [comment]
Thanks a lot

**Comment by hanke** [comment]
Replaced by gh-291

**Pull request closed without merging**
