### PR TITLE
WiP+ENH: Added duecredit stub and few citations

### PR DESCRIPTION
**Pull request by yarikoptic-private**
probably not for merge yet although should do no harm! ;)
it would result in following behavior (if duecredit is installed) if I e.g. run tests which invoke some "cited" functionality in sklearn (requires similarly patched sklearn) and pymvpa
```bash

> DUECREDIT_ENABLE=yes nosetests -s mvpa2/tests/test_clf.py mvpa2/tests/test_transerror.py
...

> duecredit summary               
DueCredit Report:
- mvpa2 (v None) [1]
  - mvpa2.clfs.transerror._call (Bayesian hypothesis testing) [4]
- sklearn (v None) [3]
  - sklearn.ensemble.forest.fit (None) [2]

2 modules cited
2 functions cited
References
----------
[1] Hanke, M. et al., 2009. PyMVPA: a Python Toolbox for Multivariate Pattern Analysis of fMRI Data. Neuroinform, 7(1), pp.37–53.
[2] Breiman, L., 2001. Random Forests. In Machine Learning. pp. 5–32.
[3] Pedregosa, F. et al., 2011. Scikit-learn: Machine Learning in Python. Journal of Machine Learning Research, 12, pp.2825–2830.
[4] Olivetti, E., Veeramachaneni, S. & Nowakowska, E., 2012. Bayesian hypothesis testing for pattern discrimination in brain decoding. Pattern Recognition, 45(6), pp.2075–2084.

$> duecredit summary --format=bibtex                                            
@article{Hanke_2009, title={PyMVPA: a Python Toolbox for Multivariate Pattern Analysis of fMRI Data}, volume={7}, ISSN={1559-0089}, url={http://dx.doi.org/10.1007/s12021-008-9041-y}, DOI={10.1007/s12021-008-9041-y}, number={1}, journal={Neuroinform}, publisher={Springer Science + Business Media}, author={Hanke, Michael and Halchenko, Yaroslav O. and Sederberg, Per B. and Hanson, Stephen José and Haxby, James V. and Pollmann, Stefan}, year={2009}, month={Jan}, pages={37–53}}
@INPROCEEDINGS{breiman2001,
    author = {Leo Breiman},
    title = {Random Forests},
    booktitle = {Machine Learning},
    year = {2001},
    pages = {5--32}
}
@article{scikit-learn,
 title={Scikit-learn: Machine Learning in {P}ython},
 author={Pedregosa, F. and Varoquaux, G. and Gramfort, A. and Michel, V.
         and Thirion, B. and Grisel, O. and Blondel, M. and Prettenhofer, P.
         and Weiss, R. and Dubourg, V. and Vanderplas, J. and Passos, A. and
         Cournapeau, D. and Brucher, M. and Perrot, M. and Duchesnay, E.},
 journal={Journal of Machine Learning Research},
 volume={12},
 pages={2825--2830},
 year={2011}
}
@article{Olivetti_2012, title={Bayesian hypothesis testing for pattern discrimination in brain decoding}, volume={45}, ISSN={0031-3203}, url={http://dx.doi.org/10.1016/j.patcog.2011.04.025}, DOI={10.1016/j.patcog.2011.04.025}, number={6}, journal={Pattern Recognition}, publisher={Elsevier BV}, author={Olivetti, Emanuele and Veeramachaneni, Sriharsha and Nowakowska, Ewa}, year={2012}, month={Jun}, pages={2075–2084}}
>
```

### CODE REVIEW

**Comment by yarikoptic** [comment]
Any objections from @PyMVPA/developers on me merging this? ;)

**Comment by nno** [comment]
Looks good, thanks. No objection to merging.

**Comment by hanke** [comment]
I object you merging this!

**Comment by hanke** [comment]
Merged it myself!

**Pull request merged**
