### PR TITLE
ENH: use more recent mdp. 

### PR DESCRIPTION
**Pull request by nno**
This may fix an issue with travis hanging during coverage testing (#368).
@yarikoptic @hanke, any objections?

### CODE REVIEW

**Comment by yarikoptic** [comment]
So they  addressed it already? Then we should cut a new mdp package for NeuroDebian

**Comment by nno** [comment]
I'm not sure what exactly is the cause of travis stalling, and/or what change (if any) in mdp is responsible for this. I did not file a report to the mdb maintainers. 

After some debugging I just noted that using a recent mdp stops the stall on travis, whereas with the NeuroDebian version, recent runs on travis is associated with a stall.

**Comment by yarikoptic** [comment]
OK, let's fix it this way then for his

**Comment by nno** [comment]
Thanks!

**Pull request merged**
