### PR TITLE
OpenFMRI enhancement

### PR DESCRIPTION
**Pull request by hanke**
Make per-trial modeling simpler.

### CODE REVIEW

**Comment by hanke** [comment]
Just to get the ball rolling...

**Comment by hanke** [comment]
@nno @yarikoptic I intent to merge this one too. I removed all the bits that were still in a "quick-hack" stage, but the remaining core bits are used quite heavily over here already.

This class will need to evolve with OpenFMRI, but there is enough demand to make it worthwhile.

Please veto if you must.

**Comment by nno** [comment]
@hanke looks good to me.

**Comment by hanke** [comment]
@nno Thanks! Merging.

**Pull request merged**
