### PR TITLE
ENH: Prevent potentially excessize memory use by default.

### PR DESCRIPTION
**Pull request by hanke**
Please merge this. Forcing the inclusion of the GLM model (as we do now) makes this unusable for the forrets gump data -- I need some 70+ GB for a simple 3 regressor fit. With this change, I can do it with 68GB less ;-)

### CODE REVIEW

**Comment by yarikoptic** [comment]
could you please Travis?

**Comment by hanke** [comment]
@yarikoptic a happy camper now...

**Comment by yarikoptic** [comment]
would you happen to please coveralls as well? ;)  e.g. by @sweepargs for providing or not the model in existing test?

**Comment by hanke** [comment]
@yarikoptic not sure what you are asking for. Running the test twice to get or not get an element in a dict that we know very little of and do nothing with? Maybe I am not getting that report, but it seem like it has very little to do with the issue at hand.

**Comment by yarikoptic** [comment]
I just reacted to decreased coverage... ok -- whatever -- merging ;-)

**Comment by hanke** [comment]
Ah, cosmetics ;-) I'll make up for those 0.01% in another PR -- promised!

**Pull request merged**
