### PR TITLE
ENH: allow scatter to load gzipped hdf5s

### PR DESCRIPTION
**Pull request by mvdoc**

### CODE REVIEW

**Comment by yarikoptic** [comment]
Haha thanks... Anyways I think that whoever ads that extension without actually using gzip to compress entire .hdf5 is misleading by adding that extension... And if it is actually gzipped it wouldn't actually work... Meanwhile merging

**Comment by yarikoptic** [comment]
Ah, missed that it wasn't just fixing the typo... So the question is either those are actually gzipped entirely?

**Comment by yarikoptic** [comment]
What is output of running file command on such a fine you have in hands? ;-)

**Comment by yarikoptic** [comment]
Fwiw failing test is unrelated

**Comment by mvdoc** [comment]
wait, why it shouldn't work? I just saved an hdf5 with `compression='gzip` and loaded w/ `h5load` and it works fine

**Comment by yarikoptic** [comment]
That is to use compression internally within hdf5 for data arrays.

**Comment by mvdoc** [comment]
OK then nevermind :-)

**Pull request closed without merging**
