### PR TITLE
deal properly with NaN values in compute_ts_boxplot_stats

### PR DESCRIPTION
**Pull request by nno**
Attempts to address #302

### CODE REVIEW

**Comment by hanke** [comment]
@nno Looks good

**Comment by nno** [comment]
As in #229, there is different behaviour depending on how recent numpy/scipy is, and now the tests fail for older versions. I'll work on a fix.

**Comment by yarikoptic** [comment]
I guess this one can get in now, @nno?

**Comment by nno** [comment]
@yarikoptic yes I think it is ready, I will merge.

**Pull request merged**
